# Generated by Django 5.1.5 on 2025-02-25 06:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
        migrations.RemoveField(
            model_name='student',
            name='course',
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default='jvsramperla2002@gmail.com', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='role_type',
            field=models.CharField(default='student', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='username',
            field=models.CharField(default='jvsram', max_length=150, unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('role_type', models.CharField(default='teacher', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
