# Generated by Django 5.1.5 on 2025-03-05 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_remove_employee_user_remove_student_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_picture',
            field=models.ImageField(default='default_profile.png', upload_to='profile_pics/'),
        ),
    ]
