# Generated by Django 5.1.5 on 2025-03-11 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_alter_student_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='college',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='current_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='permanent_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='profile_picture',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics/'),
        ),
    ]
