# Generated by Django 5.1.5 on 2025-03-14 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0005_student_college_student_current_address_student_dob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
