# Generated by Django 5.1.5 on 2025-03-14 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0007_educationdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationdetails',
            name='percentage',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
