# Generated by Django 5.1.5 on 2025-03-15 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0008_alter_educationdetails_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationdetails',
            name='degree',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='educationdetails',
            name='percentage',
            field=models.FloatField(),
        ),
    ]
