# Generated by Django 5.1.5 on 2025-03-19 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0011_remove_student_degree_remove_student_percentage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='year_of_passing',
            new_name='start_year',
        ),
        migrations.RemoveField(
            model_name='education',
            name='college',
        ),
        migrations.RemoveField(
            model_name='education',
            name='percentage',
        ),
        migrations.AddField(
            model_name='education',
            name='cgpa',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='end_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='field_of_study',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='institution',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
