# Generated by Django 5.1.5 on 2025-03-19 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0014_student_password_teacher_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='institution',
            new_name='institution_name',
        ),
        migrations.RemoveField(
            model_name='education',
            name='cgpa',
        ),
        migrations.RemoveField(
            model_name='education',
            name='end_year',
        ),
        migrations.RemoveField(
            model_name='education',
            name='start_year',
        ),
        migrations.AddField(
            model_name='education',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='grade',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='institution_logo',
            field=models.ImageField(blank=True, null=True, upload_to='education_logos/'),
        ),
        migrations.AddField(
            model_name='education',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='field_of_study',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='lms.student'),
        ),
    ]
