# Generated by Django 5.1.5 on 2025-03-20 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0016_student_skills_internship'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='languages',
            field=models.TextField(blank=True, null=True),
        ),
    ]
