# Generated by Django 5.1.5 on 2025-03-20 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0017_student_languages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='student',
            name='skills',
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='lms.student')),
            ],
        ),
    ]
