# Generated by Django 5.1.5 on 2025-03-31 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0018_remove_student_languages_remove_student_skills_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.student'),
        ),
    ]
