# Generated by Django 5.1.5 on 2025-03-31 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0019_alter_education_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='lms.student'),
        ),
    ]
