# Generated by Django 5.1.5 on 2025-04-02 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0021_teacher_college_teacher_current_address_teacher_dob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='profile_picture',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics/'),
        ),
    ]
