# Generated by Django 5.1.5 on 2025-04-02 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0022_alter_teacher_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherinternship',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='teacherskill',
            name='teacher',
        ),
        migrations.AddField(
            model_name='education',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='lms.teacher'),
        ),
        migrations.AddField(
            model_name='internship',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internships', to='lms.teacher'),
        ),
        migrations.AddField(
            model_name='skill',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='lms.teacher'),
        ),
        migrations.DeleteModel(
            name='TeacherEducation',
        ),
        migrations.DeleteModel(
            name='TeacherInternship',
        ),
        migrations.DeleteModel(
            name='TeacherSkill',
        ),
    ]
