# Generated by Django 5.1.5 on 2025-04-02 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0023_remove_teacherinternship_teacher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='lms.student'),
        ),
    ]
