# Generated by Django 5.1.5 on 2025-04-02 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0024_alter_education_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internships', to='lms.student'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='lms.student'),
        ),
    ]
