# Generated by Django 5.1.5 on 2025-04-09 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0028_course_coursecontent_enrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecontent',
            name='material',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='materials/'),
        ),
        migrations.AlterField(
            model_name='coursecontent',
            name='video',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='videos/'),
        ),
    ]
