# Generated by Django 5.1.5 on 2025-04-09 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0029_alter_coursecontent_material_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='num_lectures',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='course_thumbnails/'),
        ),
    ]
