# Generated by Django 5.1.5 on 2025-04-10 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0030_course_num_lectures_course_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='course_content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='lms.coursecontent'),
        ),
        migrations.AlterField(
            model_name='internship',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
