# Generated by Django 5.1.5 on 2025-04-11 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0032_courseprogress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseprogress',
            old_name='completed_contents',
            new_name='completed',
        ),
    ]
