# Generated by Django 5.1.5 on 2025-04-11 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0033_rename_completed_contents_courseprogress_completed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseProgress',
        ),
    ]
