# Generated by Django 5.1.5 on 2025-04-12 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0034_delete_courseprogress'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCourseProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('quiz_score', models.FloatField(blank=True, null=True)),
                ('course_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.coursecontent')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.enrollment')),
            ],
        ),
    ]
