# Generated by Django 5.1.5 on 2025-04-15 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0035_studentcourseprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='time_limit',
            field=models.IntegerField(default=10),
        ),
    ]
