# Generated by Django 5.1.5 on 2025-04-25 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0039_liveclass'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LiveClass',
        ),
    ]
