# Generated by Django 5.1.5 on 2025-04-27 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0040_delete_liveclass'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
